# Generated by Django 3.1.4 on 2021-03-03 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'In progress'), ('C', 'Completed')], default='P', max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('P', 'In progress'), ('C', 'Completed')], default='P', max_length=1)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('task_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.taskgroup')),
            ],
        ),
    ]
