# Generated by Django 3.1.4 on 2021-03-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='taskgroup',
            options={'verbose_name': 'Список задач', 'verbose_name_plural': 'Списки задач'},
        ),
    ]
