# Generated by Django 3.1.4 on 2021-03-15 21:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_guests_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guests',
            new_name='Guest',
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Гость', 'verbose_name_plural': 'Гости'},
        ),
    ]
