# Generated by Django 3.1.4 on 2021-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210331_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ceremony_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='wedding_date',
            field=models.DateField(blank=True),
        ),
    ]
